### ISSUE TITLE
installation is onerous - multiple issues

### ISSUE THREAD

**Issue by duanev** [p4lang/p4factory#192]
Been trying to install but have run into numerous issues:

- git https should be used for all subprojects: not all of us have ssh connections (https://github.com/p4lang/p4factory/issues/48), and not all of us are leet github users (I shouldn't have to generate a key to checkout a readonly copy)

- needs to work with python3

- needs to work with non Ubuntu distros (CentOS?  Arch?)

- needs to work with an Ubuntu version other than 14.04?  (is this the thrift gen-cpp issue I hit below?)

- the dependency tree is huge (multiple fonts, ipython??, etc.) ... onerous

Currently, on Ubuntu 16.04 p4factory/install_tmp/thrift-0.9.2/lib/cpp/test fails:

    gen-cpp/proc_types.cpp:17:1: error: 'MyError' does not name a type
     MyError::~MyError() throw() {
     ^
    gen-cpp/proc_types.cpp:21:6: error: 'MyError' has not been declared
     void MyError::__set_message(const std::string& val) {
          ^
    ... (several more)
    Makefile:1024: recipe for target 'gen-cpp/proc_types.lo' failed

But finally I ran across this post:  http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2017-March/000794.html   Perhaps the new hotness should be mentioned at the top of the p4factory README so we don't all go through this first?
